//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuneSharp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RuneSharp.Resources.Config", typeof(Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /m=itemdb_rs.
        /// </summary>
        internal static string BasePath {
            get {
                return ResourceManager.GetString("BasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to areaNames.json.
        /// </summary>
        internal static string BeastAreaNamesCatalogue {
            get {
                return ResourceManager.GetString("BeastAreaNamesCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to areaBeasts.json.
        /// </summary>
        internal static string BeastAreasCatalogue {
            get {
                return ResourceManager.GetString("BeastAreasCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beastData.json.
        /// </summary>
        internal static string BeastDataCatalogue {
            get {
                return ResourceManager.GetString("BeastDataCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bestiaryNames.json.
        /// </summary>
        internal static string BeastNamesCatalogue {
            get {
                return ResourceManager.GetString("BeastNamesCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beastSearch.json.
        /// </summary>
        internal static string BeastSearchCatalogue {
            get {
                return ResourceManager.GetString("BeastSearchCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bestiary.
        /// </summary>
        internal static string BestiaryApi {
            get {
                return ResourceManager.GetString("BestiaryApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /catalogue/category.json.
        /// </summary>
        internal static string CategoryCatalogue {
            get {
                return ResourceManager.GetString("CategoryCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /catalogue/detail.json.
        /// </summary>
        internal static string DetailCatalogue {
            get {
                return ResourceManager.GetString("DetailCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api.
        /// </summary>
        internal static string ExchangeApi {
            get {
                return ResourceManager.GetString("ExchangeApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /info.json.
        /// </summary>
        internal static string InfoCatalogue {
            get {
                return ResourceManager.GetString("InfoCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /catalogue/items.json.
        /// </summary>
        internal static string ItemCatalogue {
            get {
                return ResourceManager.GetString("ItemCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://services.runescape.com.
        /// </summary>
        internal static string RunescapeBaseUrl {
            get {
                return ResourceManager.GetString("RunescapeBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to services.runescape.com.
        /// </summary>
        internal static string RunescapeServices {
            get {
                return ResourceManager.GetString("RunescapeServices", resourceCulture);
            }
        }
    }
}
